### PR TITLE
Updated error codes to be more descriptive

### PR DESCRIPTION
**Pull request by phil-bystrican**
Updated error codes from 400 to something more descriptive (in this case 404 or 422).

### CODE REVIEW

**Comment by qasim** [comment]
This is a really great change 👍 we just need to update the tests so they expect the right error code.

**Comment by phil-bystrican** [comment]
These tests need to be updated for this to pass CI

athletics/test.js
buildings/test.js
courses/test.js
exams/test.js
food/test.js
textbooks/test.js
transportation/parking/test.js
transportation/shuttles/test.js

**Comment by phil-bystrican** [comment]
@qasim We're good to go

**Comment by qasim** [comment]
@phil-bystrican Nice. 😎

Thanks for the contribution.

**Pull request merged**
