### PR TITLE
Update CS Teaching Lab routes

### PR DESCRIPTION
**Pull request by arkon**
(Whoops, I forgot to do this in my own fork, but at least I made a branch??)

### CODE REVIEW

**Comment by arkon** [comment]
Might need to change the `/cdf/` part to something else though.

**Comment by kashav** [comment]
LGTM.

I think we can keep the `cdf` part for the time being, but they seem to be dropping the name altogether, so we'll definitely need to change it sometime in the future.

Maybe something like `cstl` (Computer Science Teaching Labs) or `labs` and then change the current `labs` endpoint to `computers` (so we'd have `/labs/printers` and `/labs/computers`)?

**Comment by qasim** [comment]
Thanks 😎

**Review by qasim — COMMENTED** [review]
test

**Pull request merged**
